# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef3a540e392abd2e6589a33be8f2d7fb476f358736bed89c79b2d1bd064f06ae39e89cd4aaba0071a25d6bb96706a5521ca6044abbe6bb39be24b357ad1145d7

test:
  secret_key_base: b0907665e24b85a2f3a2b504be6eea01acbc9384e0da026906da90b1639a8ef91bafaa56120dfdbda624767dd392e6040a34794f4a83bd223e04d3a204784367

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
